Server/NodeMCU_MQTT_v0.3/api/urls.py
from rest_framework import routers
from api.views import  DetectFileViewSet
from django.urls import path, include

router = routers.DefaultRouter()
router.register('/detect', DetectFileViewSet)

urlpatterns = [
    path('', include(router.urls))
]

Server/NodeMCU_MQTT_v0.3/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gateway/', include('gateway.urls')),
    path('api', include('api.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Server/NodeMCU_MQTT_v0.3/gateway/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'gateway'

urlpatterns = [
    path('upload/', upload, name = 'upload'),
    path('sec_file/', SecFileListView.as_view(), name = 'list'),
    path('sec_file/<int:pk>', SecFileDetailView.as_view(), name = 'detail'),
    path("cvt_upload/", cvt_upload, name = 'cvtUpload')
]

Server/NodeMCU_MQTT_v0.3/api/models.py
from django.db import models

# Create your models here.

Server/NodeMCU_MQTT_v0.3/gateway/models.py
from django.db import models

# Create your models here.
class SecFile(models.Model):
    file_name = models.CharField(max_length = 100)
    sec_file = models.FileField(upload_to = 'sec_file/%Y/%m/%d')
    
class DetectFile(models.Model):
    file_name = models.CharField(max_length = 100)
    sec_file = models.FileField(upload_to="convert_file/%Y/%m/%d")

Server/NodeMCU_MQTT_v0.3/api/views.py
from rest_framework import viewsets
from django.shortcuts import render
from .serializers import DetectFileSerializer
from gateway.models import DetectFile

# Create your views here.

class DetectFileViewSet(viewsets.ModelViewSet):
    queryset = DetectFile.objects.all().order_by('-id')
    serializer_class = DetectFileSerializer

Server/NodeMCU_MQTT_v0.3/gateway/views.py
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
# View 관련
from django.views import generic
# openCV
import cv2
#Haar
from .haarDetect import HarrDetect
#OS
import subprocess
import os
#Upload
from .fileUpload import fileUpload

# Create your views here.
@csrf_exempt
def upload(request):
    if request.method == "POST":
        file_name = request.POST['file_name']
        sec_file = request.FILES['sec_file']
        model = SecFile(file_name=file_name, sec_file=sec_file)
        model.save()
        
        cvt_file_name = convert(file_name)
        cvt_path = f"C:/Users/duswn/Desktop/git_repo/Gateway/Server/NodeMCU_MQTT_v0.3/{cvt_file_name}"
        cvt_url = "http://172.20.10.5:8000/gateway/cvt_upload/"
        fileUpload(cvt_path, cvt_url)
        print(f"{cvt_file_name} // Cvt Fin----!")
        os.remove(cvt_file_name)
        
        msg = {'result' : 'success'}
    else: msg = {'result' : 'fail'}
    
    return JsonResponse(msg)

def convert(file_name):
    # get Img
    y  = file_name.split("_")[0]
    imgSrc = f"./media/sec_file/{y[0:4]}/{y[4:6]}/{y[6:8]}/{file_name}"
    imgFile = cv2.imread(imgSrc)
    harrXml = "haarcascade_frontalface_alt.xml"
    
    # get Detect
    harr = HarrDetect(harrXml)
    faceLst = harr.detect(imgFile)

    getDetect = harr.draw_rect(imgFile, faceLst)
    cv2.imwrite(f"cvt_{file_name}", getDetect)
    
    return f"cvt_{file_name}"

@csrf_exempt
def cvt_upload(request):
    if request.method == "POST":
        file_name = request.POST['file_name']
        sec_file = request.FILES['sec_file']
        model = DetectFile(file_name=file_name, sec_file=sec_file)
        model.save()
        
        msg = {'result' : 'success'}
    else: msg = {'result' : 'fail'}
    
    return JsonResponse(msg)

class SecFileListView(generic.ListView):
    model = SecFile
    template_name = 'gateway/sec_file_list.html'
    context_object_name = 'sec_files' #context 변수
    
class SecFileDetailView(generic.DetailView):
    model = SecFile
    template_name = 'gateway/sec_file_detail.html'
    context_object_name = 'vfile'

Server/NodeMCU_MQTT_v0.3/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang = "ko">
    <head>
        <meta charset = "UTF-8">
        <meta http-equiv="X-UA-Compatible" content = "IE=edge">
        <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
        <Title>보안카메라_Yanjo</Title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel = "stylesheet" type = "text/css" href = "{% static 'bootstrap.min.css' %}">
        <link rel = "stylesheet" type = "text/css" href = "{% static 'style.css' %}">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
        {% block style %}{% endblock style %}
    </head>
    <body>
        <!--navbar.html을 include 하여 불러옴-->
        {% include 'navbar.html' %}
        <!--공통 템플릿-->
        <!--블럭 내에만 뭐가 들어갈지 신경쓰면 된다-->
        <div class = "container my-3">
            {% block content %}{% endblock content %}
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src = "{% static 'bootstrap.min.js' %}"></script>
        
        <!-- Delete -->
        {% block script %}{% endblock script %}
    </body>
</html>

Server/NodeMCU_MQTT_v0.3/templates/gateway/sec_file_detail.html
{% extends 'base.html' %} 

{% block content %}
<h1>보안 카메라 촬영 이미지</h1>

<!--vfile : context변수-->
<h3>{{vfile.file_name}}</h3>

<!-- 이미지 출력 -->
{% comment %} <!--비디오 재생-->
<video controls>
    <source src = "/media/{{vfile.sec_file}}" type = "video/mp4"/>
</video> {% endcomment %}
{% endblock content %}

Server/NodeMCU_MQTT_v0.3/templates/gateway/sec_file_list.html
{% extends 'base.html' %} 

{% block content %}
<h1>보안 카메라 촬영 이미지 목록</h1>
<hr>
<ul>
    {% for sec_file in sec_files %}
        <li>
            <a href = "{% url 'gateway:detail' sec_file.id %}">{{sec_file.file_name}}</a>
        </li>
    {% endfor %}
</ul>
{% endblock content %}

Server/NodeMCU_MQTT_v0.3/templates/iot/cam.html
<!DOCTYPE html>
<html lang = "ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MotionJPEG TEST</title>
    </head>
    <body>
        <div>
            <a href = "?mode=snapshot">스냅샷 보기</a> | <a href="?mode=stream">스트림 보기</a>
        </div>
        <br>
        {% if mode == "#" %} <img id = "image" />
        {% elif mode == 'snapshot' %} <img id = "imgae" src = {% url 'http://yannju:8000/mjpeg/?mode=snapshot' %}/>
        {% elif mode == 'stream' %} <img id = "imgae" src = {% url 'http://yannju@:8000/mjpeg/?mode=stream' %}/>
        {% endif %}
    </body>
</html>

Server/NodeMCU_MQTT_v0.3/templates/navbar.html
<nav class="navbar navbar-expand-sm bg-info navbar-dark">
    <a class="navbar-brand" href="#" style = "padding-left :10px">Protect Cam - YANJO</a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gateway:list' %}">목록으로 돌아가기 . . </a>
      </li>
    </ul>
  </nav>