Server/NodeMCU_MQTT_v0.4/api/urls.py
from rest_framework import routers
from api.views import SensorViewSet, SecFileViewSet
from django.urls import path, include

router = routers.DefaultRouter()
router.register('/sensor', SensorViewSet) # api/Sensor/(id) 로 들어오는 url 에 대하여 HTTP 메소드 처리
router.register('/sec_file', SecFileViewSet)

urlpatterns = [
     path('', include(router.urls))
]

Server/NodeMCU_MQTT_v0.4/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('iot/', include('iot.urls')),
    path('kakao/', include('kakao.urls')),
    path('api', include('api.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Server/NodeMCU_MQTT_v0.4/iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
    path('mqtt/', TemplateView.as_view(template_name='iot/mqtt.html')),
    path('intrusion/', detect_intrusion, name = 'intrusion'),
    path('upload/', upload, name = 'upload'),
    path('sec_file/', SecFileListView.as_view(), name = 'list'),
    path('sec_file/<int:pk>', SecFileDetailView.as_view(), name='detail'),
    path('mjpeg/', CamView.as_view(), name = 'mjpeg'),
]

Server/NodeMCU_MQTT_v0.4/kakao/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', KakaoLoginView.as_view()),
    path('oauth', KakaoAuthView.as_view(), name="oatuh"),
    path('talk', KakaoTalkView.as_view(), name = 'talk'),
]

Server/NodeMCU_MQTT_v0.4/iot/models.py
from django.db import models

# Create your models here.
class Sensor(models.Model):
    place = models.CharField(max_length=50) # Sensor 설치 장소
    category = models.CharField(max_length=50) # Sensor 종류
    value = models.FloatField() # Sensor 값
    created_at = models.DateTimeField() # Sensor 측정 날짜 - 시간
    
class SecFile(models.Model):
    file_name = models.CharField(max_length=100)
    sec_file = models.FileField(upload_to='sec_file/%Y/%m/%d/')

Server/NodeMCU_MQTT_v0.4/kakao/forms.py
from django import forms
import json
import requests

class KakaoTalkForm(forms.Form):
    text = forms.CharField(label="전송할 Talk", max_length=300)
    web_url = forms.CharField(label='Web URL', max_length=300, initial = 'http://172.20.10.5:8000/mjpeg')
    mobile_web_url = forms.CharField(label='Mobile URL', max_length = 300, initial = 'http://172.20.10.5:8000/mjepg')
    
    def send_talk(self):
        talk_url = "https://kapi.kakao.com/v2/api/talk/memo/default/send"
        with open("access_token.txt", "r") as f:
            token = f.read()
        header = {"Authorization": f"Bearer {token}"}
        # 문자열 하나, 링크 하나로 구성되는 카톡 메시지 구성
        text_template = {
            'object_type': 'text',
            'text': self.cleaned_data['text'],
            'link': {
                'web_url': self.cleaned_data['web_url'],
                'mobile_web_url': self.cleaned_data['mobile_web_url']
            }
        }
        
        print(text_template)
        payload = {'template_object': json.dumps(text_template)}
        res = requests.post(talk_url, data=payload, headers=header)
        
        return res, self.cleaned_data['text']

Server/NodeMCU_MQTT_v0.4/api/views.py
from rest_framework import viewsets
from django.shortcuts import render
from .serializers import SensorSerializer, SecFileSerializer
from iot.models import Sensor, SecFile

# Create your views here.
# viewsets 는 serializer 를 통해 응답
# HTTP method 는 Model View Set 이 처리

class SensorViewSet(viewsets.ModelViewSet):
    queryset = Sensor.objects.all().order_by('-id')
    serializer_class = SensorSerializer
    
class SecFileViewSet(viewsets.ModelViewSet):
    queryset = SecFile.objects.all().order_by('-id')
    serializer_class = SecFileSerializer

Server/NodeMCU_MQTT_v0.4/iot/views.py
from django.shortcuts import render
from . import sub
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import SecFile
# View 관련
from django.views import generic

# Create your views here.
@csrf_exempt
def upload(request):
    if request.method == "POST":
        file_name = request.POST['file_name']
        sec_file = request.FILES['sec_file']
        
        model = SecFile(file_name=file_name, sec_file=sec_file)
        model.save()
        print('upload file', file_name, sec_file)
        
        msg = {'result' : 'success'}
    else: msg = {'result' : 'fail'}
    
    return JsonResponse(msg)

def detect_intrusion(request):
    print("intrusion Detection . . .")
    print("send Notification by kakaotalk")
    
    msg = {"result" : "success"}
    return JsonResponse(msg)

class SecFileListView(generic.ListView):
    model = SecFile
    template_name = 'iot/sec_file_list.html'
    context_object_name = 'sec_files' #context 변수
    
class SecFileDetailView(generic.DetailView):
    model = SecFile
    template_name = 'iot/sec_file_detail.html'
    context_object_name = 'vfile'
    
class CamView(generic.TemplateView):
    template_name = "cam.html"
    
    def get_context_data(self):
        context = super().get_context_data()
        context['mode'] = self.request.GET.get('mode', '#')
        return context

Server/NodeMCU_MQTT_v0.4/kakao/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
# from kakao.forms import KaKaoTalkForm
import json
import requests
from django.contrib import messages
from .forms import *

# Create your views here.
client_id = '6acc3abf203ac6b3b5901880bd14d69e'

class KakaoLoginView(TemplateView):
    template_name = 'kakao_login.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["client_id"] = client_id
        
        return context
    
class KakaoAuthView(TemplateView):
    template_name = 'kakao_token.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        code = self.request.GET['code']
        token = self.getAccessToken(code)
        
        context['client_id'] = client_id
        context['token'] = token
        self.save_access_token(token["access_token"])
        
        return context
    
    # 세션 코드값 code 를 이용해서 ACESS TOKEN과 REFRESH TOKEN을 발급 받음
    def getAccessToken(self, code):
        url = "https://kauth.kakao.com/oauth/token"
        data = {
            'grant_type': 'authorization_code',
            'client_id': client_id,
            'redirect_url': 'http://172.20.10.5:8000/kakao/oauth',
            'code': code
        }
        headers = {
            'Cache-Control': "no-cache",
        }
        response = requests.post(url, data=data, headers=headers) 
        
        return response.json()
    
    def save_access_token(self, access_token):
        with open("access_token.txt", "w") as f:
            f.write(access_token)

#form class 를 쓰면 form.valid 알아서 유효성 하고 redirect
#success_url로 redirect 객체 리턴 
class KakaoTalkView(FormView):
    form_class = KakaoTalkForm
    template_name = "kakao_form.html"
    success_url = "/kakao/talk"
    
    def form_valid(self, form):
        res, text = form.send_talk()
        
        if res.json().get('result_code') == 0:
            messages.add_message(self.request, messages.SUCCESS, "메시지 전송 성공 : " + text)
        else:
            messages.add_message(self.request, messages.ERROR, "메시지 전송 실패 : " + str(res.json()))
            
        return super().form_valid(form)

Server/NodeMCU_MQTT_v0.4/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang = "ko">
    <head>
        <meta charset = "UTF-8">
        <meta http-equiv="X-UA-Compatible" content = "IE=edge">
        <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
        <Title>MQTT 테스트 . .</Title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel = "stylesheet" type = "text/css" href = "{% static 'bootstrap.min.css' %}">
        <link rel = "stylesheet" type = "text/css" href = "{% static 'style.css' %}">

        <!-- 전등 켜고/ 끄고 를 위해 필요한 링크들 . . -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
        {% block style %}{% endblock style %}
    </head>
    <body>
        <!--navbar.html을 include 하여 불러옴-->
        {% include 'navbar.html' %}
        <!--공통 템플릿-->
        <!--블럭 내에만 뭐가 들어갈지 신경쓰면 된다-->
        <div class = "container my-3">
            {% block content %}{% endblock content %}
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src = "{% static 'bootstrap.min.js' %}"></script>
        
        <!-- Delete -->
        {% block script %}{% endblock script %}
    </body>
</html>

Server/NodeMCU_MQTT_v0.4/templates/cam.html
<!DOCTYPE html>
<html lang = "ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MotionJPEG TEST</title>
    </head>
    <body>
        <div>
            <a href = "?mode=snapshot">스냅샷 보기</a> | <a href="?mode=stream">스트림 보기</a>
        </div>
        <br>
        {% if mode == "#" %} <img id = "image" />
        {% elif mode == 'snapshot' %} <img id = "image" src = {% url 'http://172.20.10.11:8000/mjpeg/snapshot' %}/>
        {% elif mode == 'stream' %} <img id = "image" src = {% url 'http://172.20.10.11:8000/mjpeg/stream' %}/>
        {% endif %}
    </body>
</html>

Server/NodeMCU_MQTT_v0.4/templates/iot/mqtt.html
{% comment %} {% extends 'base.html' %} 

{% block content %} {% endcomment %}
<div>
    <p>토픽 : <input type = 'text' id = 'topic'></p>
    <p>MESSAGE : <input type = 'text' id = 'message'></p>
    <button type = 'button' id = 'publish-btn'>전송</button>
</div>

<br>
<div class="custom-control custom-switch" id='ledIcon'>
<input type="checkbox" class="custom-control-input" id="ledcontrol">
<label class="custom-control-label" for="ledcontrol">전등</label>
</div>
<br>

<div>
    <h3>현재상태</h3>
    <div>
        조도 : <span id = 'illu'></span>
    </div>
    <div>
        온도 : <span id = 'temp'></span>℃
    </div>
    <div>
        습도 : <span id = 'humi'></span>
    </div>
</div>
<!--CDN Script-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.min.js" type="text/javascript"></script>
{% comment %} {% endblock content %} {% endcomment %}

<!--========Script===============-->
{% comment %} {% block script %} {% endcomment %}
<script>
    let btn = document.getElementById('publish-btn');
    let inputTopic = document.getElementById('topic')
    let inputMsg = document.getElementById('message');

    // 상태표시 변수
    /*
    let illu = document.getElementById('illu');
    let temp = document.getElementById('temp');
    let humi = document.getElementById('humi');
    */
    let sensors = {
        illuminate : document.getElementById('illu'),
        temperature : document.getElementById('temp'),
        humidity : document.getElementById('humi')
    };
    let historyValues = {
        illuminate : [],
        temperature :[],
        humidity : []
    };

    // 전등 켜고/끄기 변수
    let ledcontrol = document.getElementById('ledcontrol');

    /*NodeMCU Broker와 연결*/
    const BROKER_IP = 'localhost';
    const BROKER_PORT = 9001;
    const CLIENT_ID = 'clientID - ' + parseInt(Math.random() * 100);
    const SUBSCRIBE_TOPIC  = 'iot/yanjo/sensor/#';

    client = new Paho.MQTT.Client(BROKER_IP, BROKER_PORT, CLIENT_ID);
    console.log(BROKER_IP, BROKER_PORT, CLIENT_ID);

    // 발행 및 구독 준비 //
    client.onConnectionLost = onConnectionLost;
    client.onMessageArrived = onMessageArrived;

    client.connect({
        onSuccess : onConnect, // 연결 성공시 호출 콜백
        onFailure : onFailure,  // 연결 실패시 호출 콜백
    });

    // 연결전 설정 (onConnectionLost, onMessageArrived)
    function onConnectionLost(responseObject) {
        if (responseObject.errorCode !== 0) {
            console.log('onConnectionLost : ' + responseObject.errorMessage);
        }
    }

    function onMessageArrived(message) {
        console.log('topic : ' + message.destinationName);
        console.log('message : ' + message.payloadString);

        // 현재상태 할당하기 위해 split
        let parts = message.destinationName.split('/');
        /*
        if (parts.at(-1) == "illuminate") {
            illu.innerText = message.payloadString;
        }
        else if (parts.at(-1)  == "temperature") {
            temp.innerText = message.payloadString;
        }
        else if (parts.at(-1)  == "humidity") {
            humi.innerText = message.payloadString
        }
        */
        if (sensors[parts.at(-1)]) {
            sensors[parts.at(-1)].innerText = message.payloadString;
            historyValues[parts.at(-1)].push(message.payloadString);
            console.log(historyValues);
        }
        else console.log("잘못된 센서 카테고리입니다 . . .", parts.at(-1));
    }

    // 연결 설정 (onFailure, onConnect)
    function onFailure() {
        alert('Please enter host and port again . .');
    }

    function onConnect() {
        console.log('onConnect!');
        client.subscribe(SUBSCRIBE_TOPIC); // 토픽 구독
    }

    // 전송 버튼 클릭시 publish 하도록 . .
    btn.onclick = () => {
        const topic = inputTopic.value;
        const message = new Paho.MQTT.Message(inputMsg.value);

        message.destinationName = topic;
        message.qos = 1;

        client.send(message);
    }

    // 전등 제어
    ledcontrol.onclick = () => {
       // console.log(ledcontrol.checked);
       const topic = "iot/control/led";
       let msg;

       if (ledcontrol.checked) msg = "on";
       else msg = "off";
       
       const message = new Paho.MQTT.Message(msg);
       message.destinationName = topic;
       message.qos = 1;
       
       client.send(message);
    }
</script>
{% comment %} {% endblock script %} {% endcomment %}
<!--=============================-->

Server/NodeMCU_MQTT_v0.4/templates/iot/sec_file_detail.html
{% extends 'base.html' %} 

{% block content %}
<h1>보안 카메라 녹화 영상</h1>

<!--vfile : context변수-->
<h3>{{vfile.file_name}}</h3>

<!--비디오 재생-->
<video controls>
    <source src = "/media/{{vfile.sec_file}}" type = "video/mp4"/>
</video>
{% endblock content %}

Server/NodeMCU_MQTT_v0.4/templates/iot/sec_file_list.html
{% extends 'base.html' %} 

{% block content %}
<h1>보안 카메라 녹화 영상</h1>
<hr>
<ul>
    {% for sec_file in sec_files %}
        <li>
            <a href = "{% url 'iot:detail' sec_file.id %}">{{sec_file.file_name}}</a>
        </li>
    {% endfor %}
</ul>
{% endblock content %}

Server/NodeMCU_MQTT_v0.4/templates/kakao_form.html
<div>
    <h1>Talk 보내기 . . </h1>
    {% if messages %}
        {% for msg in messages %}
            <div>
                {{msg.message}}
            </div>
        {% endfor %}
    {% endif %}

    <form method = "post">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type = "submit" value = "전송ψ(._. )>`">
    </form>
</div>

Server/NodeMCU_MQTT_v0.4/templates/kakao_login.html
<h1> 카카오 로그인</h1>

<a href="https://kauth.kakao.com/oauth/authorize?client_id={{client_id}}&redirect
_uri=http://127.0.0.1:8000/kakao/oauth&response_type=code&scope=talk_message"
class="btn btn-primary">Kakao login</a>

Server/NodeMCU_MQTT_v0.4/templates/kakao_token.html
<h1>카카오 토큰 정보</h1>

{% if token.error %}
    <div>error : {{token.error}}</div>
    <div>error_description : {{token.error_description}}</div>

    <a href = "javascript : history.back()" class = "btn btn-primary">돌아가기</a>
{% else %}
    <div>access_token : {{token.access_token}}</div>
    <div>token_type : {{token.token_type}}</div>
    <div>scope : {{token.scope}}</div>
    <div>expires_in : {{token.expires_in}}</div>
    <div>refresh_token : {{token.refresh_token}}</div>
    <div>refresh_token_expires_in : {{refresh_token_expires_in}}</div>
{% endif %}

Server/NodeMCU_MQTT_v0.4/templates/navbar.html
<nav class="navbar navbar-expand-sm bg-info navbar-dark">
  <a class="navbar-brand" href="#" style = "padding-left :10px">MQTT테스트</a>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'iot:list' %}">목록으로 돌아가기 . . </a>
    </li>
  </ul>
</nav>